### ISSUE TITLE
Adição de 3 novas features

### ISSUE THREAD

**Issue by chodf** [brazil-data-cube/wtss-qgis#57]
Sugiro colocar 3 novas features:
- adição de aba com coordenadas a serem gerada as séries temporais
- função de construir e carregar raster virtual da imagem que gerou o respectivo valor do gráfico
- função para visualizar imagens de outros catálogos para inspeção por outros produtos disponibilizados pelo INPE

**Comment by raphaelrpl** [comment]
Resolvido no commit b61b5933ed001630682df8b38306d4cab9246e4b
